management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: ORDER-SERVICE
  zipkin:
    base-url: http://localhost:9411

cloud:
  loadbalancer:
    ribbon:
      enabled: false



